apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kxyf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kxyf
    app.kubernetes.io/part-of: ci1t-43256-0065-app
  name: devfile-sample-kxyf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-kxyf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-kxyf
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0065-tenant/ci1t-43256-0065-app/devfile-sample-kxyf@sha256:d54949f7bdb320007f08583311107516ab328a56dd00192a79ac2222e710b703
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
